#ifndef HARDWARE_HPP
#define HARDWARE_HPP

#define MOTOR1_PIN_PWM 14
#define MOTOR1_PIN_ENC_A 15
#define MOTOR1_PIN_ENC_B 16
#define MOTOR1_PIN_DIR 17
#define MOTOR1_CHANNEL 0

#define MOTOR2_PIN_PWM 18
#define MOTOR2_PIN_ENC_A 19
#define MOTOR2_PIN_ENC_B 20
#define MOTOR2_PIN_DIR 21
#define MOTOR2_CHANNEL 1

#define MOTOR3_PIN_PWM 22
#define MOTOR3_PIN_ENC_A 23
#define MOTOR3_PIN_ENC_B 24
#define MOTOR3_PIN_DIR 25
#define MOTOR3_CHANNEL 2

#define MOTOR4_PIN_PWM 26
#define MOTOR4_PIN_ENC_A 27
#define MOTOR4_PIN_ENC_B 28
#define MOTOR4_PIN_DIR 29
#define MOTOR4_CHANNEL 3

#define LIMIT_SWITCH_PIN 30

#define SERVO1_PINPWM 4
#define SERVO2_PINPWM 5
#define SERVO3_PINPWM 6

#endif // HARDWARE_HPP